server {
    listen 80;
    client_max_body_size 50m;

    location = / {
        return 302 /atlas/;
    }

    location /atlas {
        proxy_pass http://atlas:8080;
        proxy_set_header Host $http_host;
    }

    location /WebAPI {
        proxy_pass http://webapi:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 600s;
    }
}
